version: '3.7'

services:

  iris:
    init: true
    hostname: iris
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris
    environment:
      IRIS_USERNAME: demo
      IRIS_PASSWORD: demo
    ports:
    - "52773:52773"
    - "1972:1972"
    volumes:
    - .:/app
    - .env:/home/irisowner/.env

  jupyter:
    container_name: jupyter
    build:
      context: jupyter
    ports: 
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes: 
      - .:/app
      - ./jupyter/notebooks:/home/jovyan/
      - .env:/home/jovyan/.env
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"



